In [1]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [2]:
data = np. random.rand(7, 4)

In [3]:
data

array([[0.66446253, 0.79649177, 0.70755371, 0.25929933],
       [0.73847679, 0.94615447, 0.25424527, 0.42861117],
       [0.3914864 , 0.3336964 , 0.27149669, 0.28567709],
       [0.00387996, 0.27773153, 0.74820669, 0.43254497],
       [0.59498537, 0.45357169, 0.59242551, 0.19044433],
       [0.43910168, 0.72698036, 0.92106405, 0.52533412],
       [0.06168828, 0.61606485, 0.99634724, 0.72715274]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data [names == 'Bob']

array([[0.66446253, 0.79649177, 0.70755371, 0.25929933],
       [0.00387996, 0.27773153, 0.74820669, 0.43254497]])

In [6]:
data [names == 'Bob', 2:]

array([[0.70755371, 0.25929933],
       [0.74820669, 0.43254497]])

In [7]:
data [names == 'Bob', 3]

array([0.25929933, 0.43254497])

In [8]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [9]:
data[(names != 'Bob')]


array([[0.73847679, 0.94615447, 0.25424527, 0.42861117],
       [0.3914864 , 0.3336964 , 0.27149669, 0.28567709],
       [0.59498537, 0.45357169, 0.59242551, 0.19044433],
       [0.43910168, 0.72698036, 0.92106405, 0.52533412],
       [0.06168828, 0.61606485, 0.99634724, 0.72715274]])

In [123]:
mask = (names == 'bob') | (names == 'will')

In [124]:
mask

array([ True, False,  True,  True,  True, False, False])

In [125]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [126]:
data[(mask)]

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072]])

In [127]:
data < 0 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [128]:
data[data < 0] = 0

In [129]:
data

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [130]:
names != 'joe'

array([ True, False,  True,  True,  True, False, False])

In [131]:
data

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [132]:
data[names != 'joe'] = 7

In [133]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [10]:
arr = np.arange(15).reshape((3, 5))

In [11]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [13]:
arr = np.random.randn(6, 3)

In [15]:
np.dot(arr.T, arr)

array([[1.25199293, 0.80584999, 1.34297754],
       [0.80584999, 7.72650261, 3.09248398],
       [1.34297754, 3.09248398, 5.31005369]])

In [19]:
arr = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
               [[8, 9, 10, 11],
               [12, 13, 14, 15]]])

In [20]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [21]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [26]:
np.random.seed(1023)

In [27]:
x = np.random.rand(8)

In [28]:
np.random.seed(102)

In [33]:
y = np.random.rand(8)

In [30]:
x

array([0.91406979, 0.63007121, 0.50893322, 0.05289729, 0.03998864,
       0.73333206, 0.66635096, 0.84684819])

In [34]:
y

array([0.59768158, 0.6759869 , 0.29928174, 0.73074027, 0.57873939,
       0.80901767, 0.1672485 , 0.31214497])

In [35]:
np.maximum(x, y)

array([0.91406979, 0.6759869 , 0.50893322, 0.73074027, 0.57873939,
       0.80901767, 0.66635096, 0.84684819])

In [36]:
for i in range(len(x)):
    print(x[i], y[i])

0.9140697930834536 0.5976815849360632
0.6300712149931569 0.675986904372284
0.5089332211975177 0.29928174100970184
0.05289729466938797 0.7307402679090343
0.03998864050666828 0.5787393910609689
0.7333320588447111 0.8090176696206909
0.6663509615509096 0.16724850414891546
0.84684819272265 0.3121449685769


In [37]:
x > y

array([ True, False,  True, False, False, False,  True,  True])

In [38]:
(x > 0.5) & (y > 0.5)

array([ True,  True, False, False, False,  True, False, False])

In [39]:
(x > 0.5) | (y > 0.5)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [40]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [41]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [42]:
cond = np.array([True, False, True, True, False])

In [43]:
result = np.where(cond, xarr, yarr)

In [44]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [45]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [46]:
arr = np.random.randn(4, 4)

In [47]:
arr

array([[-0.13001637, -2.23820349,  0.97316488, -0.02418481],
       [-0.48492775, -1.10926436, -0.55897476,  1.04238657],
       [-1.71226271,  0.13611989, -0.46444399,  0.05097984],
       [ 1.44789871,  0.59313848, -0.75561568, -0.62716553]])

In [48]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2, -2],
       [-2, -2, -2,  2],
       [-2,  2, -2,  2],
       [ 2,  2, -2, -2]])

In [49]:
np.where(arr > 0, 2, arr)

array([[-0.13001637, -2.23820349,  2.        , -0.02418481],
       [-0.48492775, -1.10926436, -0.55897476,  2.        ],
       [-1.71226271,  2.        , -0.46444399,  2.        ],
       [ 2.        ,  2.        , -0.75561568, -0.62716553]])

In [56]:
x = 10 * np.random.rand(8)

In [57]:
y = 10 * np.random.rand(8)

In [58]:
np.where((x > 5) & (y < 5), 0, np.where((x > 5), 1, np.where((y < 5), 2, 3)))

array([1, 1, 0, 2, 1, 0, 1, 3])

In [59]:
for i in range(len(x)):
    print(x[i], y[i])

5.739560599458794 5.198191415311251
9.017984195830374 5.057643519558775
5.162164373002476 3.4856035962341094
4.011986415595279 0.7084276340102036
5.1748974980566045 5.759820075952406
9.373910732113611 4.017127015045218
8.504082200405826 9.114150610072178
1.7550295819612616 8.088855117422277


In [60]:
x = np.ones((5,))

In [61]:
x

array([1., 1., 1., 1., 1.])

In [62]:
y = np.linspace(-2, 2, 5)

In [63]:
y

array([-2., -1.,  0.,  1.,  2.])

In [64]:
np.outer(x, y)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [65]:
x = np.ones((4, 4))

In [66]:
x[1,:] = x[1,:] + 2

In [67]:
x[2,:] = x[2,:] * 4

In [68]:
x

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [69]:
x.mean()

2.25

In [70]:
x.mean(axis = 1)

array([1., 3., 4., 1.])

In [71]:
x.mean(axis = 0)

array([2.25, 2.25, 2.25, 2.25])

In [72]:
x.mean(1)

array([1., 3., 4., 1.])

In [73]:
x.mean(0)

array([2.25, 2.25, 2.25, 2.25])

In [74]:
x

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [75]:
x.sum()

36.0

In [76]:
x.sum(0)

array([9., 9., 9., 9.])

In [77]:
x.sum(1)

array([ 4., 12., 16.,  4.])

In [78]:
x

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [79]:
x.cumsum()

array([ 1.,  2.,  3.,  4.,  7., 10., 13., 16., 20., 24., 28., 32., 33.,
       34., 35., 36.])

In [80]:
x.cumsum(0)

array([[1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [81]:
x.sum(0)

array([9., 9., 9., 9.])

In [82]:
x.prod()

20736.0

In [83]:
x.prod(0)

array([12., 12., 12., 12.])

In [84]:
x.cumprod(0)

array([[ 1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [85]:
x = np.random.randint(1, 100, 20).reshape(5, 4)

In [86]:
x

array([[52, 55, 65, 14],
       [78, 21, 36, 69],
       [81, 75, 52, 69],
       [95, 85, 67, 24],
       [75, 73, 95, 65]])

In [87]:
x.sort(0)

In [88]:
x

array([[52, 21, 36, 14],
       [75, 55, 52, 24],
       [78, 73, 65, 65],
       [81, 75, 67, 69],
       [95, 85, 95, 69]])

In [89]:
x.sort(1)

In [90]:
x

array([[14, 21, 36, 52],
       [24, 52, 55, 75],
       [65, 65, 73, 78],
       [67, 69, 75, 81],
       [69, 85, 95, 95]])

In [91]:
np.sort(x)

array([[14, 21, 36, 52],
       [24, 52, 55, 75],
       [65, 65, 73, 78],
       [67, 69, 75, 81],
       [69, 85, 95, 95]])

In [92]:
arr = np.array([0, 1, 7, 12, 15])

In [93]:
arr.searchsorted(9)

3

In [94]:
arr.searchsorted([0, 8, 11, 15])

array([0, 3, 3, 4])

In [95]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])

In [96]:
arr.searchsorted([0, 1])

array([0, 3])

In [97]:
arr.searchsorted([0, 1], side = 'right')

array([3, 7])