# 13.11.2019 Kadir Berat YILDIRIM Ders Notu

## Advanced Numpy Examples

# The NumPy ndarray

In [2]:
data1 = [6, 7.5, 8, 0, 1]

import numpy as np

arr1 = np.array(data1)
print('array 1: ', arr1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
print('array 2: ', arr2)

array 1:  [6.  7.5 8.  0.  1. ]
array 2:  [[1 2 3 4]
 [5 6 7 8]]


In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int64')

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Data types for ndarrays

In [8]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [9]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

In [12]:
arr = np.array([1, 2, 3, 4, 5])

In [13]:
arr.dtype

dtype('int64')

In [14]:
float_arr = arr.astype(np.float64)

In [15]:
float_arr.dtype

dtype('float64')

# Array Creation Functions
- array
- asarray
- arange
- ones, ones_like
- zeros, zeros_like
- empty, empty_like
- eye, identity

# Sparse Vector

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [17]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [19]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [20]:
newarray = arr.astype(np.int32)

In [21]:
newarray

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [22]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [23]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [24]:
int_array = np.arange(10)

In [25]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [26]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [29]:
np.arange(4, 10, 2, dtype = 'float')

array([4., 6., 8.])

numpy.linspace(start, stop, num, end_point, ret_step, dtype)


In [30]:
x = np.linspace(10, 20, 5)

In [31]:
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [32]:
x = np.linspace(10, 20, 5, retstep = True)

In [33]:
x

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [34]:
x = np.linspace(10, 20, 5, endpoint = True, retstep = True)

In [35]:
x

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [36]:
x = np.linspace(10, 20, 5, endpoint = False, retstep = True)

In [37]:
x

(array([10., 12., 14., 16., 18.]), 2.0)

# Kadir Berat YILDIRIM

# Shape and dimension of an array

In [38]:
x = np.array([[2, 4, 6], [4, 6, 8]])

In [39]:
x.shape

(2, 3)

In [40]:
x.ndim

2

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.append(a, [[4, 6, 8]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 8]])

In [44]:
np.append(a, [[4], [6]], axis = 1)

array([[1, 2, 3, 4],
       [4, 5, 6, 6]])

In [45]:
array = np.array([2, 4, 4])

In [46]:
array.shape

(3,)

In [47]:
array = np.array([[2, 4, 4]])

In [48]:
array.shape

(1, 3)

In [50]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [51]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [53]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [55]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [56]:
arr - 0.5*arr

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [57]:
arr / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [58]:
arr = np.arange(10)

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr = np.array([0, 1, 2, 3, 4, 12, 12, 12, 8, 9])

In [61]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Arr slice

In [62]:
arr_slice = arr[5:8]

In [63]:
arr_slice

array([12, 12, 12])

In [64]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [65]:
arr_slice[1]

12

In [66]:
arr_slice[1] = 12345

In [67]:
arr_slice

array([   12, 12345,    12])

In [68]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [69]:
arr_slice[:]

array([   12, 12345,    12])

In [70]:
arr_slice[:] = 64

In [71]:
arr_slice

array([64, 64, 64])

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [74]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr2d[0][2]

3

In [77]:
arr2d[0,2]

3

In [78]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr3d [0]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr1

array([1., 2., 3.])

In [84]:
arr1[1:4]

array([2., 3.])

In [85]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [86]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d[1, :2]

array([4, 5])

In [92]:
arr2d[2, :1]

array([7])

In [93]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr = np.arange(8)

In [96]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [97]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [98]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [99]:
arr = np.arange(20)

In [100]:
arr.reshape((4, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
arr = np.arange(15).reshape((5, 3))

In [102]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [103]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
arr = np.arange(12).reshape((3, 4))

In [107]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [111]:
data = np.random.rand(7, 4)

In [112]:
data

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [113]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [114]:
data[names == 'bob']

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108]])

In [115]:
data[names == 'bob', 2:]

array([[0.79955295, 0.98415778],
       [0.1775666 , 0.46921108]])

In [116]:
data[names == 'bob', 3]

array([0.98415778, 0.46921108])

In [117]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [118]:
data[(names != 'bob')]

array([[0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [119]:
data[~(names == 'bob')]

array([[0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [123]:
mask = (names == 'bob') | (names == 'will')

In [124]:
mask

array([ True, False,  True,  True,  True, False, False])

In [125]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [126]:
data[(mask)]

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072]])

In [127]:
data < 0 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [128]:
data[data < 0] = 0

In [129]:
data

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [130]:
names != 'joe'

array([ True, False,  True,  True,  True, False, False])

In [131]:
data

array([[0.80490677, 0.93236063, 0.79955295, 0.98415778],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [0.90700564, 0.51708911, 0.05679803, 0.76031613],
       [0.30029869, 0.28524206, 0.1775666 , 0.46921108],
       [0.74694844, 0.9544084 , 0.58468019, 0.62513072],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])

In [132]:
data[names != 'joe'] = 7

In [133]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.52017906, 0.36234061, 0.85961008, 0.78696122],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.47338121, 0.79976376, 0.53318753, 0.49932154],
       [0.3218432 , 0.50409966, 0.01951479, 0.35073959]])