# 16.12.19 Çarşamba Kadir Berat YILDIRIM

# Elastic Net

In [2]:
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import KFold

data = pd.read_csv("Advertising.csv", index_col = 0)
model_elasticnet = linear_model.ElasticNet(alpha = 0.1, l1_ratio = 0.5)
features = ["TV","Radio","Newspaper"]
x = data[features]
y = data.Sales

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model_elasticnet,x,y,cv=5)
print (scores)
print ("average score %.2f" %scores.mean())

[0.87874334 0.91764332 0.92939993 0.81481783 0.89529628]
average score 0.89


In [3]:
import matplotlib.pyplot as plt
import numpy as np
import sklearn.datasets
#import sklearn.cross_validation as cv ### deprecated, used sklearn.model_selection instead!
import sklearn.model_selection as cv
from sklearn import linear_model

dataset = sklearn.datasets.fetch_california_housing()
X = dataset['data']
y = dataset['target']
X_train, X_test, y_train, y_test = cv.train_test_split(X, y, test_size = 0.25, random_state = 0)

model = linear_model.ElasticNetCV(cv = 5)
model.fit(X, y)
model_score = model.score(X, y)
print (model_score)
print ("alpha %.2f" % model.alpha_)
print ("l1~l ratio %.2f" % model.l1_ratio_)

0.5863093677864049
alpha 0.06
l1~l ratio 0.50


# Fitting models with Gradient Descent

Linear model fitted by minimizing a regularized empirical loss with SGD

SGD stands for Stochastic Gradient Descent: the gradient of the loss is estimated each sample at a time and the model is updated along the way with a decreasing strength schedule (aka learning rate).

Stochastic Gradient Descent (SGD) is a simple yet very efficient approach to discriminative learning of linear classifiers under convex loss functions such as (linear) Support Vector Machines and Logistic Regression. Even though SGD has been around in the machine learning community for a long time, it has received a considerable amount of attention just recently in the context of large-scale learning.

SGD has been successfully applied to large-scale and sparse machine learning problems often encountered in text classification and natural language processing. Given that the data is sparse, the classifiers in this module easily scale to problems with more than 10^5 training examples and more than 10^5 features.

The advantages of Stochastic Gradient Descent are:

        - Efficiency.

        - Ease of implementation (lots of opportunities for code tuning).

The disadvantages of Stochastic Gradient Descent include:

        - SGD requires a number of hyperparameters such as the regularization parameter and the number of iterations.

        - SGD is sensitive to feature scaling.



In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
data = [[10, 10], [20, 20], [30, 30], [40, 40]]

In [6]:
data = np.array(data)

In [7]:
data

array([[10, 10],
       [20, 20],
       [30, 30],
       [40, 40]])

In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
scaler.mean_

array([25., 25.])

In [11]:
data_scaled = scaler.transform(data)

In [12]:
data_scaled

array([[-1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079]])

In [13]:
data_scaled.mean(axis = 0)

array([0., 0.])

In [14]:
data_scaled.std(axis = 0)

array([1., 1.])

# SGD example on Boston housing data set

First scale the data.

In [16]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.linear_model import SGDRegressor
#from sklearn.cross_validation import cross_val_score ### Deprecated. Used model_selection instead!
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
#from sklearn.model_selection import train_test_split ### Deprecated. Used model_selection instead!
from sklearn.model_selection import train_test_split

data = load_boston()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

#Standardize features by removing the mean and scaling to unit variance
X_scaler = StandardScaler()
y_scaler = StandardScaler()
X_train = X_scaler.fit_transform(X_train)
y_train = y_scaler.fit_transform(y_train.reshape(-1, 1))
X_test = X_scaler.transform(X_test)
y_test = y_scaler.transform(y_test.reshape(-1, 1))

After scaling, apply SGD regression.

In [20]:
regressor = SGDRegressor(loss = 'squared_loss')
scores = cross_val_score(regressor, X_train, y_train, cv = 5)
print('Cross validation r-squared scores : ', scores)
print('Average cross validation r-squared score : ', np.mean(scores))
regressor.fit(X_train, y_train)
print('Test set r-squared score : ', regressor.score(X_test, y_test))

Cross validation r-squared scores :  [0.76027886 0.71173076 0.73798963 0.64682739 0.62230817]
Average cross validation r-squared score :  0.6958269621473854
Test set r-squared score :  0.7504507329107704


/usr/lib/python3.8/site-packages/sklearn/utils/validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3.8/site-packages/sklearn/utils/validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3.8/site-packages/sklearn/utils/validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3.8/site-packages/sklearn/utils/validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_

class sklearn.linear_model.SGDRegressor(loss='squared_loss', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate='invscaling', eta0=0.01, power_t=0.25, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, warm_start=False, average=False)

- eta0double

     The initial learning rate for the ‘constant’, ‘invscaling’ or ‘adaptive’ schedules. The default value is 0.01. 

- lossstr, default: ‘squared_loss’

    The loss function to be used. The possible values are ‘squared_loss’, ‘huber’, ‘epsilon_insensitive’, or ‘squared_epsilon_insensitive’

    The ‘squared_loss’ refers to the ordinary least squares fit. ‘huber’ modifies ‘squared_loss’ to focus less on getting outliers correct by switching from squared to     linear loss past a distance of epsilon. ‘epsilon_insensitive’ ignores errors less than epsilon and is linear past that; this is the loss function used in SVR. ‘squared_epsilon_insensitive’ is the same but becomes squared loss past a tolerance of epsilon.

- alphafloat

    Constant that multiplies the regularization term. Defaults to 0.0001 Also used to compute learning_rate when set to ‘optimal’.

- l1_ratiofloat

    The Elastic Net mixing parameter, with 0 <= l1_ratio <= 1. l1_ratio=0 corresponds to L2 penalty, l1_ratio=1 to L1. Defaults to 0.15.

- fit_interceptbool

    Whether the intercept should be estimated or not. If False, the data is assumed to be already centered. Defaults to True.

- max_iterint, optional (default=1000)

    The maximum number of passes over the training data (aka epochs). It only impacts the behavior in the fit method, and not the partial_fit method.
    
- random_stateint, RandomState instance or None, optional (default=None)

    The seed of the pseudo random number generator to use when shuffling the data. If int, random_state is the seed used by the random number generator; If RandomState instance, random_state is the random number generator; If None, the random number generator is the RandomState instance used by np.random.

- learning_ratestring, optional

    The learning rate schedule:

    ‘constant’:
        eta = eta0
        
    ‘optimal’:
        eta = 1.0 / (alpha . (t + t0)) where t0 is chosen by a heuristic proposed by Leon Bottou.
        
    ‘invscaling’: [default]
        eta = eta0 / pow(t, power_t)
        
    ‘adaptive’:
        eta = eta0, as long as the training keeps decreasing. Each time n_iter_no_change consecutive epochs fail to decrease the training loss by tol or fail to increase validation score by tol if early_stopping is True, the current learning rate is divided by 5.

In [21]:
y_predict = regressor.predict(X_test)

In [22]:
y_predict[:10]

array([ 0.5440802 , -0.32965085, -0.1026456 ,  0.23071016,  1.86689395,
        0.27163436, -0.40207811,  1.33616677, -0.71849566, -0.57749762])

In [23]:
y_scaler.inverse_transform(y_predict)

array([27.65171626, 19.58287617, 21.6792524 , 24.75776765, 39.86780104,
       25.13569955, 18.91401588, 34.96657573, 15.99192377, 17.29402998,
       33.46270381, 33.87789087, 14.94548063, 34.16295655, 17.77095582,
       22.20258791, 22.11142774, 34.00624429, 22.99386777, 24.71141603,
       31.10706043, 19.93328817, 16.30219596, 12.33606954, 15.54490523,
       12.40992601, 13.25569815,  2.23719114, 21.93647418, 17.01792384,
       21.43813619, 31.47550899, 10.22709822, 24.11851722, 24.16691725,
       43.73370067, 11.24230557, 24.66108095, 13.83880048, 30.89739891,
       24.68192498, 32.7319721 , 23.86634259, 31.90402329, 23.9598446 ,
       16.19121412, 22.87228884, 22.3247217 , 28.45565244, 17.72878874,
       13.80750868, 19.75971752, 14.47624882, 35.05088027, 23.82684195,
       35.74710997, 21.98472834, 24.7449706 , 24.06863741, 31.97980351,
        8.6280417 , 35.53914861, 23.85707244, 23.3830414 , 19.182666  ,
       34.63777904, 24.75566697, 40.93413315, 28.45434759, 26.12

In [24]:
data=pd.read_csv("credit.csv")

In [25]:
data.head()

Unnamed: 0   Income  Limit  Rating  Cards  Age  Education  Gender Student  \
0           1   14.891   3606     283      2   34         11    Male      No   
1           2  106.025   6645     483      3   82         15  Female     Yes   
2           3  104.593   7075     514      4   71         11    Male      No   
3           4  148.924   9504     681      3   36         11  Female      No   
4           5   55.882   4897     357      2   68         16    Male      No   

  Married  Ethnicity  Balance  
0     Yes  Caucasian      333  
1     Yes      Asian      903  
2      No      Asian      580  
3      No      Asian      964  
4     Yes  Caucasian      331

In [27]:
x = pd.get_dummies(data.Gender).values
y = data.Balance.values.reshape(-1, 1)

from sklearn import linear_model
from sklearn.model_selection import KFold

model = linear_model.LinearRegression(fit_intercept = False)
model.fit(x, y)

print('model score is %f ' % model.score(x, y))

model.coef_

model score is 0.000461 


array([[529.53623188, 509.80310881]])

In [28]:
data_regression = pd.get_dummies(data, columns = ['Ethnicity', 'Student', 'Gender', 'Married'])
y = data.Balance.values.reshape(-1, 1)
del data_regression['Balance']
x = data_regression.applymap(pd.to_numeric)
from sklearn import linear_model
model = linear_model.LinearRegression()
from sklearn.model_selection import RepeatedKFold
rkf = RepeatedKFold(n_splits = 4, n_repeats = 2, random_state = True)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, x, y, cv = rkf)
print('mean scores is %f' % scores.mean())

mean scores is 0.950422


In [29]:
list(data_regression.columns)

['Unnamed: 0',
 'Income',
 'Limit',
 'Rating',
 'Cards',
 'Age',
 'Education',
 'Ethnicity_African American',
 'Ethnicity_Asian',
 'Ethnicity_Caucasian',
 'Student_No',
 'Student_Yes',
 'Gender_Female',
 'Gender_Male',
 'Married_No',
 'Married_Yes']

# Polynomial Regression

- Preproccessing class offers polynomial features.

In [32]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold as kf
from sklearn.preprocessing import PolynomialFeatures
#training data
X_train = [[6], [8], [10], [14], [18]]
y_train = [[7], [9], [13], [17.5], [18]]
X_test = [[6], [8], [11], [16]]
y_test = [[0], [12], [15], [10]]

quadratic_featurizer = PolynomialFeatures(degree = 2)
X_train_quadratic = quadratic_featurizer.fit_transform(X_train)
X_test_quadratic = quadratic_featurizer.transform(X_test)
regressor_quadratic = LinearRegression()
regressor_quadratic.fit(X_train_quadratic, y_train)
print ("quadratic polynomial score is %f" % regressor_quadratic.score(X_train_quadratic, y_train))

quadratic polynomial score is 0.981642


# Regression Performance Metrics

In [33]:
from sklearn.metrics import mean_squared_error

In [34]:
y_true = [3, -0.5, 2, 7]

In [35]:
y_pred = [2.5, 0.0, 2, 8]

In [36]:
mean_squared_error(y_true, y_pred)

0.375

# Regression Metrics

In [37]:
from sklearn.metrics import mean_absolute_error

In [38]:
y_true = [3, -0.5, 2, 7]

In [39]:
y_pred = [2.5, 0.0, 2, 8]

In [41]:
mean_absolute_error(y_true, y_pred)

0.5